name: Setup Elevon
description: Set up the Elevon CLI in your GitHub Actions workflow.
author: "Erqon"
branding:
  icon: "box"
  color: "yellow"

inputs:
  version:
    description: Elevon version
    required: false
    default: latest

runs:
  using: composite
  steps:
    - name: Install Elevon
      shell: bash
      run: |
        "${{ github.action_path }}/install.sh" "${{ inputs.version }}"
