name: Elevon Deploy
description: Deploy applications with Elevon

inputs:
  version:
    description: Elevon version
    required: false
    default: latest
  project:
    description: Project name
    required: false
  config:
    description: Deployment config path
    required: false
  command:
    description: Command to run
    required: false
    default: deploy
  app:
    description: Application name(s)
    required: false

runs:
  using: composite
  steps:
    - name: Install Elevon Deploy
      shell: bash
      run: install.sh "${{ inputs.version }}"

    - name: Run Elevon
      shell: bash
      env:
        ELEVON_PROJECT: "${{ inputs.project }}"
        ELEVON_CONFIG: "${{ inputs.config }}"
        ELEVON_COMMAND: "${{ inputs.command }}"
        ELEVON_APP: "${{ inputs.app }}"
      run: run.sh
